# Created 2017-09-22 sex 17:41
#+TITLE: 
*Global Markets.* European equities are up, and the S&P future is
edging down by 0.1%. The Mexican peso is noticeably up by 0.4% against
the USD, and the yield of the 10 years Treasury is sliding to
2.25%. Commodities: oil is marginally down 0.1% to USD50.5, steel is
down 2.2% and soy prices is climbing by about 0.9%.

*Local News*. *Politics.* The second charge against Temer has finally
been sent to the Lower House. Against this background, the O Estadao
reiterates the Speaker of House discontentment with the PMDB, which
has interfered on his party's election strategy, and may impair the
processing of the charge in the House. At the other extreme, the media
outlet Broadcast informs Mr. Rogrigo Maia is, nonetheless, resolved to
get done and over with it in a expedience manner.

In addition, as we have noticed in our visit to Brasilia this week,
the O Valor noticed that PSDB looks more tamed now and,
partially sponsored by the Governor of Sao Paulo, may deliver more
votes to Temer in this time around. As expected, however, the Estadao
reports that PP, PR and PSD are again complaining about their
relationship with the government, and taking up the opportunity to
raise their stakes for more room in the government.

The presidential election race also occupies some importance. As
matter of fact, Mr. Alckmin move to sooth the government would be indeed a
step to neutralize Mr. Doria's advancements within the PMDB. In the
meantime, the latter and Mr. Rodrigo Maia seem to be in courtship
mode, after having dinner last night. Finally, according to the O
Valor, the Mr. Henrique Meirelles' name would be gathering strength
and should the economy take off for good, his candidacy could take off
for real.

*On the fiscal front*, the *Refis* comes back to the fore yet again and,
as we informed yesterday, the speculation the government may not renew
its provisional measure continues, which is raising anxieties in the
Congress, since it would like to see the approval of softer
version. Meanwhile, the *Cemig's* soup opera leaves on. Although its
auction is scheduled to next week, the companies is trying to postpone
in order to strike a last minute deal with the government.

Finally, *on the economic camp*, newspapers comes filled with optimism
on the back of a discussion over yesterday's *Quarterly Inflation*
report by the Central Bank. In a nutshell, annalists and commentators
alike are raising the bets of low interest rates for longer amid
higher GDP growth.

*Agenda - Highlights*: _Brazil_: Consumer confidence - FGV, September
and Industrial Confidence - CNI, September. _US_: Markit US PMI,
September.

|   *Time* | *Country* | *Indicator*                | *Period* | *Forecast* | *Impact* |
|----------+-----------+----------------------------+----------+------------+----------|
| 08:00:00 | BZ        | Consumer Confidence @ 82,3 | Sep      | -          | low      |
| 10:45:00 | US        | Markit Manufac.            | Sep P    | 53         | Medium   |
| 10:45:00 | US        | Markit Services            | Sep P    | 55,7       | Medium   |
| 11:00:00 | BZ        | CNI Business confidence    | Sep      | -          | Low      |

*Bottom Line*. Global markets looked mixed, while local news comes
plenty optimism, which may set a positive mode for local markets.
