# Created 2017-09-21 qui 16:07
#+OPTIONS: |:nil
#+OPTIONS: toc:nil date:nil
#+TITLE: 
*GUIDE INVESTIMENTOS: Daily Economics - 2017-09-21 qui 16:07*

*Highlights*
- *Overseas markets*: 10-years Treasury is up.
- *Local news*: The charge against Temer to go straight to the Lower
  House.
- *Watch out*: Central Bank Inflation Report and Mid-term CPI.

*Global Markets.* European equities are up, the S&P future is
unchanged. The Mexican peso, however is down by 0.2% against the USD,
and the yield of the 10 years Treasury is up to 2.27%. Commodities:
oil is down 0.3% to USD50.5, steel is down 0.4% and soy prices is
climbing about 0.7%.

*Local News*. *The second charge against Mr. Temer should indeed go to
the Lower House*, as confirmed yesterday by the Supreme Court. In
fact, according to the Estadao, the Speaker of the Lower would have
stated he is planned to get the whole done and over by before the
October 12th holiday. 

That said, the media outlet Brodacast reports Mr. Rodrigo Maia's
discontentment with PMDB, which has sponsored the entrance of the
Minister of Energy to PMDB rather than the DEM, Mr. Maia's
party. Therefore, it remains to be seen whether this affair will
interfere in the expedience of how the charge will be handled.

In the meantime, the Lower House has given an extra step to approve
*the political reform*. It started to vote, in a second round, the
constitutional amendment on election coalitions and minimum voting
thresholds, which will have to continue on next week prior to send the bill
to the Upper House, where it faces the October 7th deadline. 

Also next week, the Lower House has another daunting task: vote the
constitutional amendment on election funding, which faces the same
deadline.

*On the fiscal front*, the Refis is giving the government an extra
headache. According to the O Valor, The Ministry of Finance is no
longer interest in approving it, since, reportedly, revenues have been
quite good so far. However, Congress would be already counting on
these benefits and dissatisfaction is growing ahead of the vote of the
second charge against Temer.

On the economic front, newspaper conveys several information about
*privatizations* to come. As /per/ O Valor, the government is now
studying in more in-depth the Eletrobras' case, which it has now
floated the idea of privatization the mail services.

*Agenda - Highlights*: _Brazil_: BC's inflation report and mid-term
CPI. _US_: jobless claims.

*Bottom Line*. Global markets look a bit counter productive, while
local news look neutral.  Watch out for CB's inflation report and
mid-term inflation.

_Best Regards_,
```João Maurício Rosal, Chief Economist```
```Vinicius Alves, Economist```
